version: "3"

services:
  postgresql:
    image: postgres:10.14
    container_name: ${APP_NAME}-postgresql-apc-dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data-volume:/postgres/data:/var/lib/postgresql/data
      - postgres-init-volume:/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Asia/Tokyo
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      DATABASE_HOST: localhost
      POSTGRES_DB: db_name
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  pgadmin4:
    image: dpage/pgadmin4:6.10
    container_name: ${APP_NAME}-pgadmin4-apc-dev
    ports:
      - 8000:80
    volumes:
      - pgadmin-volume:/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: admin@abcde.com
    hostname: pgadmin4
    restart: always

  app:
    container_name: "${APP_NAME}-app"
    build: ./backend/app
    restart: always
    tty: true
    ports:
      - 80:80
    env_file: .env

volumes:
  pgadmin-volume:
  postgres-data-volume:
  postgres-init-volume: